'use client'
/*
  Auto-generated by Spline
*/
import * as THREE from 'three'
import useSpline from '@splinetool/r3f-spline'
import { OrbitControls, OrthographicCamera } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Suspense, useEffect } from 'react'
import {motion} from 'framer-motion-3d'


export default function Scene({ ...props }) {
    // useEffect(() => {
    //     document.body.style.overflow = 'hidden'
    //     return () => (document.body.style.overflow = 'auto')
    // },[]
    // )
    
    return (
        <div className="h-full ">
            <Canvas className="">
                <Suspense fallback={null}>
                    <scene>
                        <OrbitControls enableZoom={false} />
                        <color attach="background" args={["#ffffff"]} />
                        <ambientLight intensity={1.5} />
                        <pointLight position={[15, 20, 0]} castShadow  />
                        <group position={[15, 0, 0]}  rotation={[5, 15, 20]}>
                            <motion.mesh
                            initial={{ x: 10,y:0, rotateZ: 0, rotateY: 0, rotateX: 0}}
                            animate={{ x: 5,y:2, rotateZ: 1, rotateY: 0, rotateX: 2}}
                            transition={{ duration: 20, repeat: Infinity, repeatType: "reverse", ease: "easeInOut" }}
                                
                            position={[0, 0, 0]}
                                // material={materials['Silver rough']}
                            >
                                <boxGeometry  args={[7, 7, 7]} />
                                {/* <meshStandardMaterial color="#fffff"  roughness={1} /> */}

                            </motion.mesh>
                        </group>
                        <OrthographicCamera makeDefault position={[0, 0, 100]} zoom={50} />
                        {/* <hemisphereLight name="Default Ambient Light" intensity={3} position={[10,40,0]} color="#ffffff" /> */}
                        {/* Hemisphere light with shadows */}
                        <hemisphereLight name="Default Ambient Light" intensity={3} position={[10, 40, 0]} color="#ffffff" castShadow />
                        
                        {/* Directional light for shadows */}
                        <directionalLight position={[15, 10, 0]} intensity={1} castShadow shadow-mapSize={{ width: 1024, height: 1024 }} />
                    </scene>
                </Suspense>
            </Canvas>
        </div>
    )
}

